const data = {
  product: [
    {
      name: "Shirt 1",
      slug: "shirt_1",
      category: "Shirts",
      image: "/Image/Shirt-1.jpg",
      price: 90,
      brand: "Raymod",
      rating: 4.5,
      numReviews: 3,
      countInStocks: 20,
      description: "A popular Shirt",
    },
    {
      name: "Shirt 1",
      slug: "shirt_2",
      category: "Shirts",
      image: "/Image/Shirt-1.jpg",
      price: 90,
      brand: "Raymod",
      rating: 4.5,
      numReviews: 3,
      countInStocks: 20,
      description: "A popular Shirt",
    },
    {
      name: "Shirt 1",
      slug: "shirt_3",
      category: "Shirts",
      image: "/Image/Shirt-1.jpg",
      price: 90,
      brand: "Raymod",
      rating: 4.5,
      numReviews: 3,
      countInStocks: 20,
      description: "A popular Shirt",
    },
    {
      name: "Shirt 1",
      slug: "shirt_4",
      category: "Shirts",
      image: "/Image/Shirt-1.jpg",
      price: 90,
      brand: "Raymod",
      rating: 4.5,
      numReviews: 3,
      countInStocks: 20,
      description: "A popular Shirt",
    },
  ],
};

export default data;
